In [35]:
import numpy as np

### Броадкастинг

In [36]:
x = np.array([1, 2, 3])
a = 5

In [37]:
x*a

array([ 5, 10, 15])

x = [1, 2, 3]
a = 5 -> a = [5, 5, 5]

In [38]:
x = np.ones((2, 3, 5, 1))
y = np.ones((2, 1, 5, 8))

x*y

array([[[[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
 

In [39]:
c = x*y
c.shape

(2, 3, 5, 8)

In [40]:
x.shape, y.shape

((2, 3, 5, 1), (2, 1, 5, 8))

In [41]:
x = np.ones((3, 5, 1))
y = np.ones((2, 1, 5, 8))


In [42]:
z = x*y
z.shape

(2, 3, 5, 8)

In [43]:
x = np.ones((3, 5, 1))
y = np.ones((2, 4, 5, 8))

x*y

ValueError: operands could not be broadcast together with shapes (3,5,1) (2,4,5,8) 

In [ ]:
a = np.ones((3, 5, 4, 1))

In [ ]:
a.shape, a.ndim

((3, 5, 4, 1), 4)

In [ ]:
a.reshape(3, 5, 2, 1, 2)

array([[[[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]]],



       [[[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]]],



       [[[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]]]])

In [ ]:
a

array([[[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]]])

In [ ]:
a = np.resize(a, (3, 5, 4, 3))
print(a)

[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]]


In [ ]:
b = np.ones((3, 5, 4, 1))
b.resize((3, 5, 4, 2))

In [ ]:
b.resize()

array([[[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
   

In [ ]:
a = np.ones((3, 500, 1000))

In [ ]:
3*w*h

In [ ]:
1*kanal*1*w*1*h

In [ ]:
expand_dims

In [ ]:
a.shape
# 0, 2, 4

(3, 500, 1000)

In [ ]:
b = np.expand_dims(a, axis=(0, 2, 4))
b.shape

(1, 3, 1, 500, 1, 1000)

In [ ]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
np.expand_dims(a, axis=(0, 2))

array([[[1],
        [2],
        [3]]])

In [ ]:
b.squeeze(axis=(0, 2)).shape

(3, 500, 1, 1000)

In [ ]:
np.pad(a, pad_width=(2, 3), mode='edge')

array([1, 1, 1, 2, 3, 3, 3, 3])

In [ ]:
b.reshape(3, 500, 200, -1).shape

(3, 500, 200, 5)

### Делаем массивы плоскими

In [ ]:
b.shape # -> 1500000

(1, 3, 1, 500, 1, 1000)

In [ ]:
c = np.ravel(b)
c.shape, b.shape

((1500000,), (1, 3, 1, 500, 1, 1000))

In [ ]:
b.ravel()

array([1., 1., 1., ..., 1., 1., 1.])

In [ ]:
b.flatten()

array([1., 1., 1., ..., 1., 1., 1.])

In [ ]:
np.flatten(b)

AttributeError: module 'numpy' has no attribute 'flatten'

In [ ]:
type(b.reshape(-1))

numpy.ndarray

In [ ]:
a = np.array([[1, 2, 3], [3, 4, 5]])
a, list(a)

(array([[1, 2, 3],
        [3, 4, 5]]),
 [array([1, 2, 3]), array([3, 4, 5])])

In [ ]:
type(a.tolist()[0])

list

### Преобразование массивов (вставка, разбивка)

In [ ]:
a = np.array([[1, 2, 3], [3, 4, 5], [3, 3, 2]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [3, 3, 2]])

In [ ]:
a.shape

(2, 3)

In [ ]:
np.split(a, 3, axis=1)

[array([[1],
        [3]]),
 array([[2],
        [4]]),
 array([[3],
        [5]])]

In [ ]:
a.shape

(2, 3)

In [ ]:
np.insert(a, (1, 2), (1000, 500), axis=1)

array([[   1, 1000,    2,  500,    3],
       [   3, 1000,    4,  500,    5],
       [   3, 1000,    3,  500,    2]])

In [ ]:
a.shape

(3, 3)

In [ ]:
np.append(a, values=[[100], [100]])

array([  1,   2,   3,   3,   4,   5, 100, 100])

In [ ]:
a = np.append(a, [[1, 2, 3]], axis=0)

In [ ]:
a = np.append(a, [[1], [1], [1]], axis=1)

In [ ]:
a

array([[1, 2, 3, 1],
       [3, 4, 5, 1],
       [1, 2, 3, 1]])

In [ ]:
els, inxs = np.unique(a, axis=0, return_index=True)

In [ ]:
els

array([[1, 2, 3, 1],
       [3, 4, 5, 1]])

In [ ]:
inxs

array([0, 1], dtype=int64)

In [ ]:
els, inxs = np.unique(a, axis=0, return_inverse=True)

In [ ]:
els, inxs

(array([[1, 2, 3, 1],
        [3, 4, 5, 1]]),
 array([0, 1, 0], dtype=int64))

In [ ]:
els[inxs]

array([[1, 2, 3, 1],
       [3, 4, 5, 1],
       [1, 2, 3, 1]])

In [ ]:
els, cnt = np.unique(a, axis=0, return_counts=True)

In [ ]:
els, cnt

(array([[1, 2, 3, 1],
        [3, 4, 5, 1]]),
 array([2, 1], dtype=int64))

In [ ]:
np.tile(a, (1, 3))

array([[1, 2, 3, 1, 1, 2, 3, 1, 1, 2, 3, 1],
       [3, 4, 5, 1, 3, 4, 5, 1, 3, 4, 5, 1],
       [1, 2, 3, 1, 1, 2, 3, 1, 1, 2, 3, 1]])

In [ ]:
np.repeat(a, 3, axis=1)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1],
       [3, 3, 3, 4, 4, 4, 5, 5, 5, 1, 1, 1],
       [1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1]])

Объединение массивов и конкатенация

In [ ]:
a

array([[1, 2, 3, 1],
       [3, 4, 5, 1],
       [1, 2, 3, 1]])

In [ ]:
b = np.repeat(a, 3, axis=1)

In [ ]:
np.concatenate((a, b), axis=1)

array([[1, 2, 3, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1],
       [3, 4, 5, 1, 3, 3, 3, 4, 4, 4, 5, 5, 5, 1, 1, 1],
       [1, 2, 3, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1]])

In [ ]:
c = a.copy()

In [ ]:
np.concatenate((a, c*2), axis=1)

array([[ 1,  2,  3,  1,  2,  4,  6,  2],
       [ 3,  4,  5,  1,  6,  8, 10,  2],
       [ 1,  2,  3,  1,  2,  4,  6,  2]])

In [ ]:
a.shape, b.shape

((3, 4), (3, 12))

In [ ]:
np.hstack((a, b))

array([[1, 2, 3, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1],
       [3, 4, 5, 1, 3, 3, 3, 4, 4, 4, 5, 5, 5, 1, 1, 1],
       [1, 2, 3, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1]])

In [ ]:
np.vstack((a, b))
# stack, dstack

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 12

#### Другие полезные функции

In [ ]:
a

array([[1, 2, 3, 1],
       [3, 4, 5, 1],
       [1, 2, 3, 1]])

In [ ]:
a.prod(axis=0)

array([ 3, 16, 45,  1])

In [ ]:
np.array([]).prod()

1.0

In [ ]:
b = a*1.02568

In [ ]:
b

array([[1.02568, 2.05136, 3.07704, 1.02568],
       [3.07704, 4.10272, 5.1284 , 1.02568],
       [1.02568, 2.05136, 3.07704, 1.02568]])

In [ ]:
b.round(2)

array([[1.03, 2.05, 3.08, 1.03],
       [3.08, 4.1 , 5.13, 1.03],
       [1.03, 2.05, 3.08, 1.03]])

In [ ]:
a.sort()

In [ ]:
np.sort(b, axis=0)

array([[1.02568, 2.05136, 3.07704, 1.02568],
       [1.02568, 2.05136, 3.07704, 1.02568],
       [3.07704, 4.10272, 5.1284 , 1.02568]])

In [ ]:
np.argsort(b, axis=None)

array([ 0,  3,  7,  8, 11,  1,  9,  2,  4, 10,  5,  6], dtype=int64)

In [ ]:
arr = np.array([1, 2, 0, 3, 5, -4, 2])
np.argmin(arr)

5

In [ ]:
np.argmax(arr)

4

In [ ]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.diag(a, k=-1)

array([5])

#### WHERE - фильтрация

In [ ]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.where(a%2 == 1)

(array([0, 0, 1, 1, 1], dtype=int64), array([1, 3, 0, 2, 4], dtype=int64))

In [ ]:
a[np.where(a%2 == 1)]

array([1, 3, 5, 7, 9])

In [ ]:
np.where((a%2 == 1) & (a > 3))

(array([1, 1, 1], dtype=int64), array([0, 2, 4], dtype=int64))

In [ ]:
np.where(np.logical_and(a%2 == 1, a > 3))

(array([1, 1, 1], dtype=int64), array([0, 2, 4], dtype=int64))

In [ ]:
np.where((a%2 == 1) | (a > 3))

(array([0, 0, 0, 1, 1, 1, 1, 1], dtype=int64),
 array([1, 3, 4, 0, 1, 2, 3, 4], dtype=int64))

In [ ]:
np.where(np.logical_or(a%2 == 1, a > 3))

(array([0, 0, 0, 1, 1, 1, 1, 1], dtype=int64),
 array([1, 3, 4, 0, 1, 2, 3, 4], dtype=int64))

In [ ]:
np.where(a > 5, a, -1)

array([[-1, -1, -1, -1, -1],
       [-1,  6,  7,  8,  9]])

In [ ]:
np.where(a > 5, a, a**2)

array([[ 0,  1,  4,  9, 16],
       [25,  6,  7,  8,  9]])