In [1]:
import numpy as np

### Статистика в Numpy

In [49]:
a = np.array([
    [
        [1, 2, 3],
        [4, 10, 7]
    ],
    [
        [101, 13, 28],
        [44, 5, 18]
    ]
    ])
a

array([[[  1,   2,   3],
        [  4,  10,   7]],

       [[101,  13,  28],
        [ 44,   5,  18]]])

In [50]:
a.shape

(2, 2, 3)

In [59]:
a.ptp(axis=(1, 2))

array([ 9, 96])

In [55]:
a.max() - a.min()

100

In [ ]:
[1, 2]

In [61]:
np.percentile(a, 50, axis=(1, 2), method='closest_observation')

array([ 3, 18])

In [62]:
np.quantile(a, 0.5, axis=(1, 2), method='closest_observation')

array([ 3, 18])

In [65]:
np.median(a, axis=(1, 2))

array([ 3.5, 23. ])

In [67]:
a.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [69]:
np.average(a, axis=(1, 2))

array([ 4.5       , 34.83333333])

In [71]:
np.var(a, axis=(1, 2))

array([   9.58333333, 1026.47222222])

In [72]:
a

array([[[  1,   2,   3],
        [  4,  10,   7]],

       [[101,  13,  28],
        [ 44,   5,  18]]])

In [73]:
np.std(a, axis=(1, 2))

array([ 3.09569594, 32.03860519])

In [74]:
32.03860519**2

1026.472222520695

In [77]:
a.var(axis=(1, 2))

array([   9.58333333, 1026.47222222])

In [78]:
x = np.random.rand(3, 3)

In [79]:
x

array([[0.86991454, 0.03462553, 0.76832166],
       [0.42609381, 0.03165717, 0.45364675],
       [0.37762002, 0.57209851, 0.90523419]])

In [83]:
np.corrcoef(x, rowvar=False)

array([[ 1.        , -0.57145563,  0.13362131],
       [-0.57145563,  1.        ,  0.73691526],
       [ 0.13362131,  0.73691526,  1.        ]])

In [86]:
np.cov(x)

array([[0.20772314, 0.10604692, 0.0047288 ],
       [0.10604692, 0.05573577, 0.01306795],
       [0.0047288 , 0.01306795, 0.07119633]])

In [85]:
y = np.random.rand(3, 3)
np.cov(x, y)

array([[ 0.20772314,  0.10604692,  0.0047288 , -0.0136998 ,  0.09463511,
        -0.17512735],
       [ 0.10604692,  0.05573577,  0.01306795, -0.0105386 ,  0.04711164,
        -0.08464064],
       [ 0.0047288 ,  0.01306795,  0.07119633, -0.02396341, -0.00586296,
         0.02781134],
       [-0.0136998 , -0.0105386 , -0.02396341,  0.00877251, -0.00357399,
         0.00097066],
       [ 0.09463511,  0.04711164, -0.00586296, -0.00357399,  0.04401833,
        -0.08337119],
       [-0.17512735, -0.08464064,  0.02781134,  0.00097066, -0.08337119,
         0.16186982]])