In [1]:
import numpy as np

### Линейная алгебра

In [31]:
a = np.random.rand(3, 5)
b = np.random.rand(5, 3)

In [32]:
a

array([[0.64029219, 0.6828146 , 0.80001664, 0.26686485, 0.48003154],
       [0.3013639 , 0.21650239, 0.6463554 , 0.53774667, 0.41474146],
       [0.3679051 , 0.56148129, 0.31400908, 0.78585439, 0.49704575]])

In [33]:
b

array([[0.32843099, 0.7913661 , 0.40754101],
       [0.41022794, 0.05424736, 0.6469149 ],
       [0.58877558, 0.26383956, 0.76569501],
       [0.69400866, 0.0020697 , 0.62303499],
       [0.86852127, 0.95150455, 0.89486873]])

In [34]:
np.dot(a, b)

array([[1.5635558 , 1.21212699, 1.91106837],
       [1.30176347, 0.81650934, 1.46396203],
       [1.51313217, 0.87902229, 1.68800769]])

In [35]:
np.matmul(a, b)

array([[1.5635558 , 1.21212699, 1.91106837],
       [1.30176347, 0.81650934, 1.46396203],
       [1.51313217, 0.87902229, 1.68800769]])

In [36]:
a @ b

array([[1.5635558 , 1.21212699, 1.91106837],
       [1.30176347, 0.81650934, 1.46396203],
       [1.51313217, 0.87902229, 1.68800769]])

In [37]:
np.dot(a, 5)

array([[3.20146096, 3.41407301, 4.00008319, 1.33432424, 2.40015771],
       [1.50681952, 1.08251197, 3.231777  , 2.68873334, 2.07370728],
       [1.8395255 , 2.80740647, 1.57004538, 3.92927193, 2.48522873]])

In [38]:
np.matmul(5, b)

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [40]:
np.linalg.multi_dot((a, b, a))

array([[2.06951569, 2.40307626, 2.63442829, 2.57089679, 2.20316382],
       [1.61817452, 1.88762662, 2.02888502, 1.93693107, 1.69118389],
       [1.85477894, 2.17128391, 2.30874145, 2.20302134, 1.92993519]])

In [41]:
a @ b @ a

array([[2.06951569, 2.40307626, 2.63442829, 2.57089679, 2.20316382],
       [1.61817452, 1.88762662, 2.02888502, 1.93693107, 1.69118389],
       [1.85477894, 2.17128391, 2.30874145, 2.20302134, 1.92993519]])

In [42]:
c = np.array([1, 2, 3])
d = np.array([4, 5, 6])

In [44]:
np.inner(c, d)

32

In [46]:
np.outer(c, d)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [47]:
a

array([[0.64029219, 0.6828146 , 0.80001664, 0.26686485, 0.48003154],
       [0.3013639 , 0.21650239, 0.6463554 , 0.53774667, 0.41474146],
       [0.3679051 , 0.56148129, 0.31400908, 0.78585439, 0.49704575]])

In [48]:
np.trace(a)

1.1708036613927777

In [50]:
e = np.random.rand(3, 3)
np.linalg.det(e)

-0.03493088402880332

In [52]:
np.linalg.eig(e)

(array([ 1.30657331, -0.15670405,  0.1706065 ]),
 array([[ 0.21652575,  0.77842453, -0.49110055],
        [ 0.33350233, -0.57073087, -0.53234319],
        [ 0.91754716,  0.26138385,  0.68951503]]))

In [53]:
np.linalg.eigvals(e)

array([ 1.30657331, -0.15670405,  0.1706065 ])

Ax = B

In [56]:
np.linalg.solve(e, c)

array([ 4.93470292e+00,  2.33663378e+00, -2.28226966e-03])