In [ ]:
# Урок 2. Основные операции с массивами

In [3]:
import numpy as np

In [85]:
a = np.array([1, 2, 3, 4, 5])

In [86]:
a

array([1, 2, 3, 4, 5])

In [87]:
type(a)

numpy.ndarray

In [88]:
print(a)

[1 2 3 4 5]


In [89]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]

a = np.array(arr)

In [91]:
a.shape

(9,)

In [92]:
a.ndim

1

In [93]:
a.dtype

dtype('int32')

In [94]:
a = np.array(arr, dtype=np.float64)

In [96]:
a.dtype

dtype('float64')

In [97]:
a.astype(np.int32)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
np.array([1, 2, 'ddd']).dtype

dtype('<U11')

In [101]:
arr = [1, 2, 3, 4, 5, 6, 7, 8]

a = np.asarray(arr)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [102]:
b = np.array([1, 2, 0, 4, 5, 6, 7, 8])

In [103]:
b

array([1, 2, 0, 4, 5, 6, 7, 8])

In [106]:
a + b

array([ 2,  4,  3,  8, 10, 12, 14, 16])

In [107]:
a - b

array([0, 0, 3, 0, 0, 0, 0, 0])

In [108]:
a*b

array([ 1,  4,  0, 16, 25, 36, 49, 64])

In [109]:
a / b

C:\Users\User\AppData\Local\Temp/ipykernel_11660/1286629031.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a / b


array([ 1.,  1., inf,  1.,  1.,  1.,  1.,  1.])

In [113]:
np.divide(a, b)

C:\Users\User\AppData\Local\Temp/ipykernel_11660/3737392904.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(a, b)


array([ 1.,  1., inf,  1.,  1.,  1.,  1.,  1.])

In [111]:
[1, 2] / [1, 1]

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [114]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [115]:
a.sum()

36

In [116]:
a.mean()

4.5

In [117]:
a.min()

1

## Многомерные массивы

In [118]:
arr2 = [[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]
print(arr2)

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]


In [119]:
b = np.array(arr2)
b

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [120]:
b.shape

(2, 5)

In [121]:
b.ndim

2

In [122]:
c = np.array(arr2)

In [123]:
b + c

array([[ 2,  4,  6,  8, 10],
       [ 2,  4,  6,  8, 10]])

In [124]:
b / c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [126]:
b

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [130]:
b.sum(axis=1)

array([15, 15])

In [171]:
arr3 = [
    [
        [1, 2, 3, 4, 5],
        [8, 2, 3, 4, 5]
    ], 
    [
        [1, 2, 3, 4, 5],
        [115, 2, 3, 4, 5]
    ], 
    [
        [1, 2, 3, 4, 5], 
        [1024, 2, 3, 4, 5]
    ]
]

c = np.array(arr3, dtype=np.int64)

In [172]:
c

array([[[   1,    2,    3,    4,    5],
        [   8,    2,    3,    4,    5]],

       [[   1,    2,    3,    4,    5],
        [ 115,    2,    3,    4,    5]],

       [[   1,    2,    3,    4,    5],
        [1024,    2,    3,    4,    5]]], dtype=int64)

In [173]:
c.shape

(3, 2, 5)

In [134]:
c.ndim

3

In [150]:
c.mean(axis=2)

array([[3., 3.],
       [3., 3.],
       [3., 3.]], dtype=float32)

In [177]:
c.sum(axis=2)

array([[  15,   22],
       [  15,  129],
       [  15, 1038]], dtype=int64)

In [178]:
c.sum(axis=(0, 1))

array([1150,   12,   18,   24,   30], dtype=int64)

In [182]:
arr4 = [
    [
        [1000, 2, 3, 4, 5], 
        [1000, 2, 3, 4, 5],
        [1000, 2, 3, 4, 5]           
    ], 
    [
        [1000, 2, 3, 4, 5], 
        [1000, 2, 3, 4, 5],
        [1000, 2, 3, 4, 5]   
    ], 
    [
        [1000, 2, 3, 4, 5], 
        [1000, 2, 3, 4, 5],
        [1000, 2, 3, 4, 5]   
    ]
]

d = np.array(arr4, dtype=np.int64)

In [183]:
c.shape, d.shape

((3, 2, 5), (3, 3, 5))

In [184]:
c + d

ValueError: operands could not be broadcast together with shapes (3,2,5) (3,3,5) 

In [185]:
arr1 = np.array([[1, 2, 3], [1, 2, 3]])
arr2 = np.array([3, 4, 5])
arr1 + arr2

array([[4, 6, 8],
       [4, 6, 8]])

In [188]:
np.eye(5, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [189]:
np.eye(5, 10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [190]:
np.zeros((3, 5, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [192]:
a = np.empty((2, 3, 5))

In [195]:
a[0, 0, 0]

0.0

In [196]:
np.full((2, 3, 5), fill_value=15)

array([[[15, 15, 15, 15, 15],
        [15, 15, 15, 15, 15],
        [15, 15, 15, 15, 15]],

       [[15, 15, 15, 15, 15],
        [15, 15, 15, 15, 15],
        [15, 15, 15, 15, 15]]])

In [197]:
np.ones((2, 3, 5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [198]:
np.ones_like(a)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [199]:
range(0, 10, 0.1)

TypeError: 'float' object cannot be interpreted as an integer

In [200]:
np.arange(0, 10, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [201]:
np.linspace(0, 10, 7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [203]:
c

array([[[   1,    2,    3,    4,    5],
        [   8,    2,    3,    4,    5]],

       [[   1,    2,    3,    4,    5],
        [ 115,    2,    3,    4,    5]],

       [[   1,    2,    3,    4,    5],
        [1024,    2,    3,    4,    5]]], dtype=int64)

In [204]:
c.shape

(3, 2, 5)

In [211]:
c[2, 1, 0]

1024

In [212]:
c[1:, :1, 2:]

array([[[3, 4, 5]],

       [[3, 4, 5]]], dtype=int64)

In [213]:
a = c[0, 1]

In [215]:
a.shape

(5,)

In [217]:
a

array([8, 2, 3, 4, 5], dtype=int64)

In [219]:
a[1:3]

array([2, 3], dtype=int64)

In [220]:
a[::-1]

array([5, 4, 3, 2, 8], dtype=int64)

In [221]:
a[::2]

array([8, 3, 5], dtype=int64)

In [226]:
a[1:4:2] = 100
a

array([  8, 100,   3, 100,   5], dtype=int64)

In [227]:
a

array([  8, 100,   3, 100,   5], dtype=int64)

In [228]:
b = a

In [229]:
b

array([  8, 100,   3, 100,   5], dtype=int64)

In [230]:
b[::3] = 1000
b

array([1000,  100,    3, 1000,    5], dtype=int64)

In [231]:
a

array([1000,  100,    3, 1000,    5], dtype=int64)

In [232]:
c = a.copy()
print(c, a)
c[1] = 10000
print(c, a)

[1000  100    3 1000    5] [1000  100    3 1000    5]
[ 1000 10000     3  1000     5] [1000  100    3 1000    5]
