In [1]:
import numpy as np

### Логические функции

In [67]:
a = np.array([[1, 2, 3, np.nan, True], [4, np.inf, 5, np.NINF, False], [False, False, 0, False, False]])

In [54]:
a

array([[  1.,   2.,   3.,  nan],
       [  4.,  inf,   5., -inf]])

In [60]:
np.all(a, axis=1)

array([ True, False])

In [68]:
np.any(a, axis=1)

array([ True,  True, False])

In [76]:
np.inf, np.NINF, np.nan, np.NaN, np.NAN

(inf, -inf, nan, nan, nan)

In [77]:
np.isfinite(a)

array([[ True,  True,  True, False,  True],
       [ True, False,  True, False,  True],
       [ True,  True,  True,  True,  True]])

In [78]:
a

array([[  1.,   2.,   3.,  nan,   1.],
       [  4.,  inf,   5., -inf,   0.],
       [  0.,   0.,   0.,   0.,   0.]])

In [79]:
np.isinf(a)

array([[False, False, False, False, False],
       [False,  True, False,  True, False],
       [False, False, False, False, False]])

In [80]:
np.isnan(a)

array([[False, False, False,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [81]:
c = np.ones(a.shape)
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [82]:
np.isnan(a, out=c)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [84]:
c = np.isnan(a)

In [86]:
c

array([[False, False, False,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [87]:
d = np.array([0.000005, 0.000006, 0.000007])
e = d + 1e-6

In [89]:
e, d

(array([6.e-06, 7.e-06, 8.e-06]), array([5.e-06, 6.e-06, 7.e-06]))

In [91]:
np.isclose(e, d, atol=1e-7)

array([False, False, False])

In [94]:
np.allclose(e, d, atol=1e-7)

False

In [95]:
b = a.copy()

In [96]:
a == b

array([[ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [98]:
np.array_equal(a, b, equal_nan=True)

True

In [101]:
np.equal(a, b)

array([[ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [102]:
np.less_equal(a, b)

array([[ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [103]:
np.less(a, b)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])